server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itbrijesh/central-config-repository
          searchPaths: microservice1
          username: itbrijesh
          password: Brijesh123